### ISSUE TITLE
Disadvantage Counter

### ISSUE THREAD

**Issue by ericcberg** [YanKlInnomme/FoundryVTT-k4lt#19]
Just got done putting in all of the book Disadvantages and noticed something with the counter. It seems to take the value as the starting value and allows it to be increased beyond that number. It should, I believe, start the counter at 0 and use the value put in as the maximum value. (Unless, of course, I'm using it wrong.)

**Comment by YanKlInnomme** [comment]
The value entered in the item corresponds to the maximum value. The counter displayed therefore corresponds to a countdown. I have deliberately not blocked the value so that it can be adapted as required during the game. For example, a Condemned may, with the support of a powerful entity, benefit from a sursie of 5, so the counter can be increased to 15.
